import plugins.spotify.main
from modules.app import input_playlist

if __name__ == "__main__":
    # song_data = pull_songs()
    # print(song_data[0], len(song_data))
    # playlist_data = pull_playlists()
    # print(playlist_data[4]["songs"][0], len(playlist_data))
    # ping()
    unidentified_songs = [
        {
            "service_id": "spotify",
            "artist_id": "",
            "input_artist_name": "Yonkagor",
            "song_id": "",
            "input_song_title": "Another mistake",
            "db_song_id": None,
        },
        {
            "service_id": "spotify",
            "artist_id": "",
            "input_artist_name": "Yuki Shysuki",
            "song_id": "",
            "input_song_title": "Nightcore AMV ~ RISE (FRENCH VERS. +PAROLES)",
            "db_song_id": None,
        },
    ]

    unidentified_songs_db = [
        {
            "service_id": "spotify",
            "artist_id": "7jy3rLJdDQY21OgRLCZ9sD",
            "artist_name": "Foo Fighters",
            "input_artist_name": "Foo Fighters",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Ain't It The Life (from Skin And Bones, Live in Hollywood, 2006)",
            "db_song_id": 5636,
        },
        {
            "service_id": "spotify",
            "artist_id": "20JZFwl6HVl6yg8a4H3ZqK",
            "artist_name": "Panic! At The Disco",
            "input_artist_name": "Panic! At The Disco",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Golden Days",
            "db_song_id": 1506,
        },
        {
            "service_id": "spotify",
            "artist_id": "20JZFwl6HVl6yg8a4H3ZqK",
            "artist_name": "Panic! At The Disco",
            "input_artist_name": "Panic! At The Disco",
            "song_id": None,
            "song_title": None,
            "input_song_title": "House of Memories (slowed down version)",
            "db_song_id": 5677,
        },
        {
            "service_id": "spotify",
            "artist_id": "20JZFwl6HVl6yg8a4H3ZqK",
            "artist_name": "Panic! At The Disco",
            "input_artist_name": "Panic! At The Disco",
            "song_id": None,
            "song_title": None,
            "input_song_title": "LA Devotee",
            "db_song_id": 5753,
        },
        {
            "service_id": "spotify",
            "artist_id": "20JZFwl6HVl6yg8a4H3ZqK",
            "artist_name": "Panic! At The Disco",
            "input_artist_name": "Panic! At The Disco",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Nicotine",
            "db_song_id": 5694,
        },
        {
            "service_id": "spotify",
            "artist_id": "4FpJcNgOvIpSBeJgRg3OfN",
            "artist_name": "Orelsan",
            "input_artist_name": "Orelsan",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Athéna",
            "db_song_id": 5971,
        },
        {
            "service_id": "spotify",
            "artist_id": "4FpJcNgOvIpSBeJgRg3OfN",
            "artist_name": "Orelsan",
            "input_artist_name": "Orelsan",
            "song_id": None,
            "song_title": None,
            "input_song_title": "CP_001_Intro Civilisation Perdue",
            "db_song_id": 5972,
        },
        {
            "service_id": "spotify",
            "artist_id": "4FpJcNgOvIpSBeJgRg3OfN",
            "artist_name": "Orelsan",
            "input_artist_name": "Orelsan",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Rêves bizarres (feat. Damso)",
            "db_song_id": 5973,
        },
        {
            "service_id": "spotify",
            "artist_id": "27IjlIOwlo59ZWM9pJq8Gv",
            "artist_name": "Dimrain47",
            "input_artist_name": "Dimrain47",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Dimrain47 - (7) Forsaken Neon",
            "db_song_id": 1275,
        },
        {
            "service_id": "spotify",
            "artist_id": "27IjlIOwlo59ZWM9pJq8Gv",
            "artist_name": "Dimrain47",
            "input_artist_name": "Dimrain47",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Dimrain47 - The Disturbance",
            "db_song_id": 5780,
        },
        {
            "service_id": "spotify",
            "artist_id": "1b6ywCGaEtyV4JUfGYKmk8",
            "artist_name": "Kennyoung",
            "input_artist_name": "Kennyoung",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Machine Gun Kelly - Concert For Aliens (Cover)",
            "db_song_id": 5711,
        },
        {
            "service_id": "spotify",
            "artist_id": "1b6ywCGaEtyV4JUfGYKmk8",
            "artist_name": "Kennyoung",
            "input_artist_name": "Kennyoung",
            "song_id": None,
            "song_title": None,
            "input_song_title": "The Network - Roshambo (Cover)",
            "db_song_id": 1353,
        },
        {
            "service_id": "spotify",
            "artist_id": "1b6ywCGaEtyV4JUfGYKmk8",
            "artist_name": "Kennyoung",
            "input_artist_name": "Kennyoung",
            "song_id": None,
            "song_title": None,
            "input_song_title": "kennyoung & YonKaGor - See You!",
            "db_song_id": 5709,
        },
        {
            "service_id": "spotify",
            "artist_id": "1b6ywCGaEtyV4JUfGYKmk8",
            "artist_name": "Kennyoung",
            "input_artist_name": "Kennyoung",
            "song_id": None,
            "song_title": None,
            "input_song_title": "kennyoung - Nothing",
            "db_song_id": 5707,
        },
        {
            "service_id": "spotify",
            "artist_id": "1b6ywCGaEtyV4JUfGYKmk8",
            "artist_name": "Kennyoung",
            "input_artist_name": "Kennyoung",
            "song_id": None,
            "song_title": None,
            "input_song_title": "kennyoung - Suicider",
            "db_song_id": 1427,
        },
        {
            "service_id": "spotify",
            "artist_id": "6Wn6kyMvfESmIaVy3Sjjvf",
            "artist_name": "CircusP",
            "input_artist_name": "CircusP",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Last of Me",
            "db_song_id": 5845,
        },
        {
            "service_id": "spotify",
            "artist_id": "2M1EOE4J6tnaLCfMhE3eFq",
            "artist_name": "YonKaGor",
            "input_artist_name": "YonKaGor",
            "song_id": None,
            "song_title": None,
            "input_song_title": '"K.K. Disco" Fishboy Remix (Animal Crossing)',
            "db_song_id": 6250,
        },
        {
            "service_id": "spotify",
            "artist_id": "2M1EOE4J6tnaLCfMhE3eFq",
            "artist_name": "YonKaGor",
            "input_artist_name": "YonKaGor",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Another Mistake (Karaoke)",
            "db_song_id": 1498,
        },
        {
            "service_id": "spotify",
            "artist_id": "2M1EOE4J6tnaLCfMhE3eFq",
            "artist_name": "YonKaGor",
            "input_artist_name": "YonKaGor",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Artificial Abandonment",
            "db_song_id": 5670,
        },
        {
            "service_id": "spotify",
            "artist_id": "2M1EOE4J6tnaLCfMhE3eFq",
            "artist_name": "YonKaGor",
            "input_artist_name": "YonKaGor",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Butcher Vanity (cover/arrangement)",
            "db_song_id": 1287,
        },
        {
            "service_id": "spotify",
            "artist_id": "2M1EOE4J6tnaLCfMhE3eFq",
            "artist_name": "YonKaGor",
            "input_artist_name": "YonKaGor",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Dandelion 🌼 (Full Song)",
            "db_song_id": 5632,
        },
        {
            "service_id": "spotify",
            "artist_id": "2M1EOE4J6tnaLCfMhE3eFq",
            "artist_name": "YonKaGor",
            "input_artist_name": "YonKaGor",
            "song_id": None,
            "song_title": None,
            "input_song_title": "I Forgot That You Exist (Karaoke)",
            "db_song_id": 6290,
        },
        {
            "service_id": "spotify",
            "artist_id": "2M1EOE4J6tnaLCfMhE3eFq",
            "artist_name": "YonKaGor",
            "input_artist_name": "YonKaGor",
            "song_id": None,
            "song_title": None,
            "input_song_title": "My Castle Town - Cover/Arrangement/Remix",
            "db_song_id": 1500,
        },
        {
            "service_id": "spotify",
            "artist_id": "2M1EOE4J6tnaLCfMhE3eFq",
            "artist_name": "YonKaGor",
            "input_artist_name": "YonKaGor",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Rempong (song sketch)",
            "db_song_id": 5671,
        },
        {
            "service_id": "spotify",
            "artist_id": "2M1EOE4J6tnaLCfMhE3eFq",
            "artist_name": "YonKaGor",
            "input_artist_name": "YonKaGor",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Telecaster B-Boy (Cover/Arrangement)",
            "db_song_id": 6238,
        },
        {
            "service_id": "spotify",
            "artist_id": "2M1EOE4J6tnaLCfMhE3eFq",
            "artist_name": "YonKaGor",
            "input_artist_name": "YonKaGor",
            "song_id": None,
            "song_title": None,
            "input_song_title": "You'll Be Gone (Instrumental)",
            "db_song_id": 5628,
        },
        {
            "service_id": "spotify",
            "artist_id": "2M1EOE4J6tnaLCfMhE3eFq",
            "artist_name": "YonKaGor",
            "input_artist_name": "YonKaGor",
            "song_id": None,
            "song_title": None,
            "input_song_title": "[TW] Top 10 Things To Do Before You Die (Censored)",
            "db_song_id": 6258,
        },
        {
            "service_id": "spotify",
            "artist_id": "3WCGPWxaTtnBgGQj4w7LEW",
            "artist_name": "Scratch21",
            "input_artist_name": "Scratch21",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Scratch21 - Sorry Jack [Official Music Video]",
            "db_song_id": 5767,
        },
        {
            "service_id": "spotify",
            "artist_id": "3WCGPWxaTtnBgGQj4w7LEW",
            "artist_name": "Scratch21",
            "input_artist_name": "Scratch21",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Scratch21 - Strangers feat. EileMonty [Lyric Video]",
            "db_song_id": 1358,
        },
        {
            "service_id": "spotify",
            "artist_id": "3WCGPWxaTtnBgGQj4w7LEW",
            "artist_name": "Scratch21",
            "input_artist_name": "Scratch21",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Scratch21 - The Rhyme [Lyric Video]",
            "db_song_id": 1355,
        },
        {
            "service_id": "spotify",
            "artist_id": "5j4HeCoUlzhfWtjAfM1acR",
            "artist_name": "Stromae",
            "input_artist_name": "Stromae",
            "song_id": None,
            "song_title": None,
            "input_song_title": "carmen [blank]",
            "db_song_id": 6182,
        },
        {
            "service_id": "spotify",
            "artist_id": "7xUEVAixJOG51xLGQvRCLH",
            "artist_name": "AZALI",
            "input_artist_name": "AZALI",
            "song_id": None,
            "song_title": None,
            "input_song_title": "DIVINITY DISSONANT",
            "db_song_id": 5804,
        },
        {
            "service_id": "spotify",
            "artist_id": "7xUEVAixJOG51xLGQvRCLH",
            "artist_name": "AZALI",
            "input_artist_name": "AZALI",
            "song_id": None,
            "song_title": None,
            "input_song_title": "tiny fire rat (battle)",
            "db_song_id": 1281,
        },
        {
            "service_id": "spotify",
            "artist_id": "0SwO7SWeDHJijQ3XNS7xEE",
            "artist_name": "MGMT",
            "input_artist_name": "MGMT",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Little Dark Age (Official Viedo)",
            "db_song_id": 5880,
        },
        {
            "service_id": "spotify",
            "artist_id": "0SwO7SWeDHJijQ3XNS7xEE",
            "artist_name": "MGMT",
            "input_artist_name": "MGMT",
            "song_id": None,
            "song_title": None,
            "input_song_title": "When You Die",
            "db_song_id": 5891,
        },
        {
            "service_id": "spotify",
            "artist_id": "0yNLKJebCb8Aueb54LYya3",
            "artist_name": "New Order",
            "input_artist_name": "New Order",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Blue Monday ’88",
            "db_song_id": 5892,
        },
        {
            "service_id": "spotify",
            "artist_id": "57DlMWmbVIf2ssJ8QBpBau",
            "artist_name": "Toby Fox",
            "input_artist_name": "Toby Fox",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Battle Against A True Hero",
            "db_song_id": 1604,
        },
        {
            "service_id": "spotify",
            "artist_id": "57DlMWmbVIf2ssJ8QBpBau",
            "artist_name": "Toby Fox",
            "input_artist_name": "Toby Fox",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Bird That Carries You Over A Disproportionately Small Gap",
            "db_song_id": 5847,
        },
        {
            "service_id": "spotify",
            "artist_id": "57DlMWmbVIf2ssJ8QBpBau",
            "artist_name": "Toby Fox",
            "input_artist_name": "Toby Fox",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Bonetrousle",
            "db_song_id": 1601,
        },
        {
            "service_id": "spotify",
            "artist_id": "57DlMWmbVIf2ssJ8QBpBau",
            "artist_name": "Toby Fox",
            "input_artist_name": "Toby Fox",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Don't Forget (feat. Laura Shigihara)",
            "db_song_id": 6300,
        },
        {
            "service_id": "spotify",
            "artist_id": "57DlMWmbVIf2ssJ8QBpBau",
            "artist_name": "Toby Fox",
            "input_artist_name": "Toby Fox",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Finale",
            "db_song_id": 1587,
        },
        {
            "service_id": "spotify",
            "artist_id": "57DlMWmbVIf2ssJ8QBpBau",
            "artist_name": "Toby Fox",
            "input_artist_name": "Toby Fox",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Heartache",
            "db_song_id": 1603,
        },
        {
            "service_id": "spotify",
            "artist_id": "57DlMWmbVIf2ssJ8QBpBau",
            "artist_name": "Toby Fox",
            "input_artist_name": "Toby Fox",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Here We Are",
            "db_song_id": 6283,
        },
        {
            "service_id": "spotify",
            "artist_id": "57DlMWmbVIf2ssJ8QBpBau",
            "artist_name": "Toby Fox",
            "input_artist_name": "Toby Fox",
            "song_id": None,
            "song_title": None,
            "input_song_title": "His Theme",
            "db_song_id": 1589,
        },
        {
            "service_id": "spotify",
            "artist_id": "57DlMWmbVIf2ssJ8QBpBau",
            "artist_name": "Toby Fox",
            "input_artist_name": "Toby Fox",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Memory",
            "db_song_id": 1584,
        },
        {
            "service_id": "spotify",
            "artist_id": "57DlMWmbVIf2ssJ8QBpBau",
            "artist_name": "Toby Fox",
            "input_artist_name": "Toby Fox",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Metal Crusher",
            "db_song_id": 1602,
        },
        {
            "service_id": "spotify",
            "artist_id": "57DlMWmbVIf2ssJ8QBpBau",
            "artist_name": "Toby Fox",
            "input_artist_name": "Toby Fox",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Undertale",
            "db_song_id": 1586,
        },
        {
            "service_id": "spotify",
            "artist_id": "57DlMWmbVIf2ssJ8QBpBau",
            "artist_name": "Toby Fox",
            "input_artist_name": "Toby Fox",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Undertale Remixed ▸ Megalovania ▸ Holder Remix",
            "db_song_id": 1607,
        },
        {
            "service_id": "spotify",
            "artist_id": "57DlMWmbVIf2ssJ8QBpBau",
            "artist_name": "Toby Fox",
            "input_artist_name": "Toby Fox",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Undertale ▸ His Theme ▸ Sprightly Remix",
            "db_song_id": 1557,
        },
        {
            "service_id": "spotify",
            "artist_id": "57DlMWmbVIf2ssJ8QBpBau",
            "artist_name": "Toby Fox",
            "input_artist_name": "Toby Fox",
            "song_id": None,
            "song_title": None,
            "input_song_title": "sans.",
            "db_song_id": 1588,
        },
        {
            "service_id": "spotify",
            "artist_id": "22y08IZx7u6SWpsfap1Cub",
            "artist_name": "Rio Romeo",
            "input_artist_name": "Rio Romeo",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Soft Bitch",
            "db_song_id": 5956,
        },
        {
            "service_id": "spotify",
            "artist_id": "77JLoURVdxC8jnr3DPY05x",
            "artist_name": "Tanger",
            "input_artist_name": "Tanger",
            "song_id": None,
            "song_title": None,
            "input_song_title": "! PARTY SIRENS !",
            "db_song_id": 5787,
        },
        {
            "service_id": "spotify",
            "artist_id": "77JLoURVdxC8jnr3DPY05x",
            "artist_name": "Tanger",
            "input_artist_name": "Tanger",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Joysticks",
            "db_song_id": 5800,
        },
        {
            "service_id": "spotify",
            "artist_id": "77JLoURVdxC8jnr3DPY05x",
            "artist_name": "Tanger",
            "input_artist_name": "Tanger",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Nano",
            "db_song_id": 5799,
        },
        {
            "service_id": "spotify",
            "artist_id": "77JLoURVdxC8jnr3DPY05x",
            "artist_name": "Tanger",
            "input_artist_name": "Tanger",
            "song_id": None,
            "song_title": None,
            "input_song_title": "downpour.remastered",
            "db_song_id": 5798,
        },
        {
            "service_id": "spotify",
            "artist_id": "77JLoURVdxC8jnr3DPY05x",
            "artist_name": "Tanger",
            "input_artist_name": "Tanger",
            "song_id": None,
            "song_title": None,
            "input_song_title": "merry fuсking christmas",
            "db_song_id": 1320,
        },
        {
            "service_id": "spotify",
            "artist_id": "77JLoURVdxC8jnr3DPY05x",
            "artist_name": "Tanger",
            "input_artist_name": "Tanger",
            "song_id": None,
            "song_title": None,
            "input_song_title": "strangers once again (with Treb) [Official MV]",
            "db_song_id": 1280,
        },
        {
            "service_id": "spotify",
            "artist_id": "77JLoURVdxC8jnr3DPY05x",
            "artist_name": "Tanger",
            "input_artist_name": "Tanger",
            "song_id": None,
            "song_title": None,
            "input_song_title": "taraxaWHAT",
            "db_song_id": 5788,
        },
        {
            "service_id": "spotify",
            "artist_id": "77JLoURVdxC8jnr3DPY05x",
            "artist_name": "Tanger",
            "input_artist_name": "Tanger",
            "song_id": None,
            "song_title": None,
            "input_song_title": "tiny windows (feat. Frizk)",
            "db_song_id": 5797,
        },
        {
            "service_id": "spotify",
            "artist_id": "1N1JZ3SRv6PSzAsOEW2aZp",
            "artist_name": "Bear Ghost",
            "input_artist_name": "Bear Ghost",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Necromancin Dancin",
            "db_song_id": 1341,
        },
        {
            "service_id": "spotify",
            "artist_id": "04gDigrS5kc9YWfZHwBETP",
            "artist_name": "Maroon 5",
            "input_artist_name": "Maroon 5",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Lost (Official Music Video)",
            "db_song_id": 5678,
        },
        {
            "service_id": "spotify",
            "artist_id": "6s22t5Y3prQHyaHWUN1R1C",
            "artist_name": "AJR",
            "input_artist_name": "AJR",
            "song_id": None,
            "song_title": None,
            "input_song_title": "AJR - 100 Bad Days (Official Video)",
            "db_song_id": 5680,
        },
        {
            "service_id": "spotify",
            "artist_id": "6s22t5Y3prQHyaHWUN1R1C",
            "artist_name": "AJR",
            "input_artist_name": "AJR",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Burn The House Down",
            "db_song_id": 1503,
        },
        {
            "service_id": "spotify",
            "artist_id": "6s22t5Y3prQHyaHWUN1R1C",
            "artist_name": "AJR",
            "input_artist_name": "AJR",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Weak",
            "db_song_id": 5687,
        },
        {
            "service_id": "spotify",
            "artist_id": "1iGwHlKgQKtdrtzmlwZ71U",
            "artist_name": "Nico Collins",
            "input_artist_name": "Nico Collins",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Nico Collins - Borderline",
            "db_song_id": 6292,
        },
        {
            "service_id": "spotify",
            "artist_id": "0ybFZ2Ab08V8hueghSXm6E",
            "artist_name": "Opeth",
            "input_artist_name": "Opeth",
            "song_id": None,
            "song_title": None,
            "input_song_title": "The Grand Conjuration",
            "db_song_id": 1340,
        },
        {
            "service_id": "spotify",
            "artist_id": "36QJpDe2go2KgaRleHCDTp",
            "artist_name": "Led Zeppelin",
            "input_artist_name": "Led Zeppelin",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Immigrant Song (Remaster)",
            "db_song_id": 5873,
        },
        {
            "service_id": "spotify",
            "artist_id": "4gzpq5DPGxSnKTe4SA8HAU",
            "artist_name": "Coldplay",
            "input_artist_name": "Coldplay",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Viva la Vida",
            "db_song_id": 1417,
        },
        {
            "service_id": "spotify",
            "artist_id": "4fnono0JCZFAeeaecrI7kg",
            "artist_name": "Solence",
            "input_artist_name": "Solence",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Animal in Me (live at SXM Octane Virtual Accelerator Concert)",
            "db_song_id": 1457,
        },
        {
            "service_id": "spotify",
            "artist_id": "53XhwfbYqKCa1cC15pYq2q",
            "artist_name": "Imagine Dragons",
            "input_artist_name": "Imagine Dragons",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Bad Liar – Stripped",
            "db_song_id": 5752,
        },
        {
            "service_id": "spotify",
            "artist_id": "53XhwfbYqKCa1cC15pYq2q",
            "artist_name": "Imagine Dragons",
            "input_artist_name": "Imagine Dragons",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Whatever It Takes (Official Music Video)",
            "db_song_id": 5879,
        },
        {
            "service_id": "spotify",
            "artist_id": "3GCo22R8vSTHqSP5mYM1E7",
            "artist_name": "AJ Dispirito",
            "input_artist_name": "AJ Dispirito",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Eternal Dream (feat. Elsie Lovelock)",
            "db_song_id": 5794,
        },
        {
            "service_id": "spotify",
            "artist_id": "1x2YcZB1QpRZB3HT9gdUCQ",
            "artist_name": "Ken Ashcorp",
            "input_artist_name": "Ken Ashcorp",
            "song_id": None,
            "song_title": None,
            "input_song_title": "I Wish There Were Still Dinosaurs",
            "db_song_id": 1451,
        },
        {
            "service_id": "spotify",
            "artist_id": "1dWEYMPtNmvSVaDNLgB6NV",
            "artist_name": "Saint Motel",
            "input_artist_name": "Saint Motel",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Puzzle Pieces",
            "db_song_id": 1407,
        },
        {
            "service_id": "spotify",
            "artist_id": "3u6lPufHw4Oww6D88rv6sB",
            "artist_name": "Penelope Scott",
            "input_artist_name": "Penelope Scott",
            "song_id": None,
            "song_title": None,
            "input_song_title": "7 O'Clock",
            "db_song_id": 6277,
        },
        {
            "service_id": "spotify",
            "artist_id": "3u6lPufHw4Oww6D88rv6sB",
            "artist_name": "Penelope Scott",
            "input_artist_name": "Penelope Scott",
            "song_id": None,
            "song_title": None,
            "input_song_title": "American Healthcare",
            "db_song_id": 5846,
        },
        {
            "service_id": "spotify",
            "artist_id": "6m2jVlh2H1muI95k4LcN3L",
            "artist_name": "Nick Nitro",
            "input_artist_name": "Nick Nitro",
            "song_id": None,
            "song_title": None,
            "input_song_title": 'Bad Time Trio [Undertale AU] - "Triple The Threat" NITRO Remix',
            "db_song_id": 1595,
        },
        {
            "service_id": "spotify",
            "artist_id": "6m2jVlh2H1muI95k4LcN3L",
            "artist_name": "Nick Nitro",
            "input_artist_name": "Nick Nitro",
            "song_id": None,
            "song_title": None,
            "input_song_title": 'Inktale [Undertale AU] - "Tokyovania Control" NITRO Remix',
            "db_song_id": 5732,
        },
        {
            "service_id": "spotify",
            "artist_id": "6m2jVlh2H1muI95k4LcN3L",
            "artist_name": "Nick Nitro",
            "input_artist_name": "Nick Nitro",
            "song_id": None,
            "song_title": None,
            "input_song_title": 'Inktale [Undertale AU] - "Tokyovania" V3 NITRO Remix',
            "db_song_id": 1572,
        },
        {
            "service_id": "spotify",
            "artist_id": "6m2jVlh2H1muI95k4LcN3L",
            "artist_name": "Nick Nitro",
            "input_artist_name": "Nick Nitro",
            "song_id": None,
            "song_title": None,
            "input_song_title": 'Storyshift [Undertale AU] - "Devilovania [Chara Strikes Back/Insantion]" NITRO Remix',
            "db_song_id": 1605,
        },
        {
            "service_id": "spotify",
            "artist_id": "6m2jVlh2H1muI95k4LcN3L",
            "artist_name": "Nick Nitro",
            "input_artist_name": "Nick Nitro",
            "song_id": None,
            "song_title": None,
            "input_song_title": 'Storyshift [Undertale AU] - "Devilovania" V2 NITRO Remix',
            "db_song_id": 1559,
        },
        {
            "service_id": "spotify",
            "artist_id": "6m2jVlh2H1muI95k4LcN3L",
            "artist_name": "Nick Nitro",
            "input_artist_name": "Nick Nitro",
            "song_id": None,
            "song_title": None,
            "input_song_title": 'Touhou: EoSD - "UN. Owen Was Her" NITRO Remix',
            "db_song_id": 5580,
        },
        {
            "service_id": "spotify",
            "artist_id": "6m2jVlh2H1muI95k4LcN3L",
            "artist_name": "Nick Nitro",
            "input_artist_name": "Nick Nitro",
            "song_id": None,
            "song_title": None,
            "input_song_title": 'Underfell [Undertale AU] - "M.E.G.A.L.O.V.A.N.I.A."  NITRO Remix',
            "db_song_id": 5745,
        },
        {
            "service_id": "spotify",
            "artist_id": "6m2jVlh2H1muI95k4LcN3L",
            "artist_name": "Nick Nitro",
            "input_artist_name": "Nick Nitro",
            "song_id": None,
            "song_title": None,
            "input_song_title": 'Undertale - "Chara\'s Theme [Megalo Strike Back]" NITRO Remix V2',
            "db_song_id": 1569,
        },
        {
            "service_id": "spotify",
            "artist_id": "6m2jVlh2H1muI95k4LcN3L",
            "artist_name": "Nick Nitro",
            "input_artist_name": "Nick Nitro",
            "song_id": None,
            "song_title": None,
            "input_song_title": 'Undertale - "Do Or Die [Battle Against A True Hero]" NITRO Remix',
            "db_song_id": 5737,
        },
        {
            "service_id": "spotify",
            "artist_id": "6m2jVlh2H1muI95k4LcN3L",
            "artist_name": "Nick Nitro",
            "input_artist_name": "Nick Nitro",
            "song_id": None,
            "song_title": None,
            "input_song_title": 'Undertale - "Hopes And Dreams & Save The World!" NITRO Remix [5k Special]',
            "db_song_id": 5734,
        },
        {
            "service_id": "spotify",
            "artist_id": "6m2jVlh2H1muI95k4LcN3L",
            "artist_name": "Nick Nitro",
            "input_artist_name": "Nick Nitro",
            "song_id": None,
            "song_title": None,
            "input_song_title": 'Undertale - "Monster In The Mirror" NITRO Remix',
            "db_song_id": 1514,
        },
        {
            "service_id": "spotify",
            "artist_id": "6m2jVlh2H1muI95k4LcN3L",
            "artist_name": "Nick Nitro",
            "input_artist_name": "Nick Nitro",
            "song_id": None,
            "song_title": None,
            "input_song_title": 'Undertale - "Undertale Theme" NITRO Remix',
            "db_song_id": 5573,
        },
        {
            "service_id": "spotify",
            "artist_id": "6m2jVlh2H1muI95k4LcN3L",
            "artist_name": "Nick Nitro",
            "input_artist_name": "Nick Nitro",
            "song_id": None,
            "song_title": None,
            "input_song_title": 'Undertale - "Virtue\'s Vengeance" v3 NITRO Remix',
            "db_song_id": 1513,
        },
        {
            "service_id": "spotify",
            "artist_id": "6m2jVlh2H1muI95k4LcN3L",
            "artist_name": "Nick Nitro",
            "input_artist_name": "Nick Nitro",
            "song_id": None,
            "song_title": None,
            "input_song_title": 'Undertale Disbelief - "Megalo Strike Back X Interstellar Retribution" [Phase 2] NITRO Remix',
            "db_song_id": 5585,
        },
        {
            "service_id": "spotify",
            "artist_id": "6m2jVlh2H1muI95k4LcN3L",
            "artist_name": "Nick Nitro",
            "input_artist_name": "Nick Nitro",
            "song_id": None,
            "song_title": None,
            "input_song_title": 'Undertale Disbelief - "Painful Retribution" [Phase 5 Hardmode] NITRO Remix',
            "db_song_id": 5582,
        },
        {
            "service_id": "spotify",
            "artist_id": "6m2jVlh2H1muI95k4LcN3L",
            "artist_name": "Nick Nitro",
            "input_artist_name": "Nick Nitro",
            "song_id": None,
            "song_title": None,
            "input_song_title": 'Undertale OST - "Asgore\'s Battle Theme" V2 NITRO Remix',
            "db_song_id": 5736,
        },
        {
            "service_id": "spotify",
            "artist_id": "6m2jVlh2H1muI95k4LcN3L",
            "artist_name": "Nick Nitro",
            "input_artist_name": "Nick Nitro",
            "song_id": None,
            "song_title": None,
            "input_song_title": 'Underverse [Undertale AU] - "Cross Sans Theme" NITRO Remix',
            "db_song_id": 1540,
        },
        {
            "service_id": "spotify",
            "artist_id": "4T7KICeQg50AwFzauMCR9C",
            "artist_name": "Derivakat",
            "input_artist_name": "Derivakat",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Froggy Song - Derivakat ft. BoomerNA",
            "db_song_id": 6280,
        },
        {
            "service_id": "spotify",
            "artist_id": "4T7KICeQg50AwFzauMCR9C",
            "artist_name": "Derivakat",
            "input_artist_name": "Derivakat",
            "song_id": None,
            "song_title": None,
            "input_song_title": "HONEY - Derivakat",
            "db_song_id": 6299,
        },
        {
            "service_id": "spotify",
            "artist_id": "2kCcBybjl3SAtIcwdWpUe3",
            "artist_name": "Lil Peep",
            "input_artist_name": "Lil Peep",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Lil Peep & XXXTENTACION - Falling Down",
            "db_song_id": 5698,
        },
        {
            "service_id": "spotify",
            "artist_id": "4rF7c8zpCKzuSXohs2HIpA",
            "artist_name": "Steven Universe",
            "input_artist_name": "Steven Universe",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Steven Universe The Movie - Change (feat. Zach Callison) - (OFFICIAL VIDEO)",
            "db_song_id": 1439,
        },
        {
            "service_id": "spotify",
            "artist_id": "5dHfLBNU8zoypgKefzEB1c",
            "artist_name": "Pomplamoose",
            "input_artist_name": "Pomplamoose",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Aerosmith - I Don't Wanna Miss A Thing",
            "db_song_id": 1437,
        },
        {
            "service_id": "spotify",
            "artist_id": "5dHfLBNU8zoypgKefzEB1c",
            "artist_name": "Pomplamoose",
            "input_artist_name": "Pomplamoose",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Harder, Better, Faster, Stronger",
            "db_song_id": 1428,
        },
        {
            "service_id": "spotify",
            "artist_id": "5dHfLBNU8zoypgKefzEB1c",
            "artist_name": "Pomplamoose",
            "input_artist_name": "Pomplamoose",
            "song_id": None,
            "song_title": None,
            "input_song_title": "I Will Survive + This Love Mashup (feat. Andie Case)",
            "db_song_id": 1426,
        },
        {
            "service_id": "spotify",
            "artist_id": "5dHfLBNU8zoypgKefzEB1c",
            "artist_name": "Pomplamoose",
            "input_artist_name": "Pomplamoose",
            "song_id": None,
            "song_title": None,
            "input_song_title": "The Weeknd + Michael Jackson + Justin Timberlake Mashup - Pomplamoose",
            "db_song_id": 1423,
        },
        {
            "service_id": "spotify",
            "artist_id": "2Waw2sSbqvAwK8NwACNjVo",
            "artist_name": "Bo Burnham",
            "input_artist_name": "Bo Burnham",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Repeat Stuff",
            "db_song_id": 1470,
        },
        {
            "service_id": "spotify",
            "artist_id": "6IOp54e0ZK9Ccnb8WUIeUa",
            "artist_name": "kroh",
            "input_artist_name": "kroh",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Hush [ft. Mizz Fish]",
            "db_song_id": 6294,
        },
        {
            "service_id": "spotify",
            "artist_id": "6IOp54e0ZK9Ccnb8WUIeUa",
            "artist_name": "kroh",
            "input_artist_name": "kroh",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Mr. Bones [ft. DropsteR & Kanaya]",
            "db_song_id": 6278,
        },
        {
            "service_id": "spotify",
            "artist_id": "6WArR4J31WsWrqVfVtKRTC",
            "artist_name": "Nightmargin",
            "input_artist_name": "Nightmargin",
            "song_id": None,
            "song_title": None,
            "input_song_title": "LcdDem OST - Tower",
            "db_song_id": 6274,
        },
        {
            "service_id": "spotify",
            "artist_id": "45Thh01bYz4UDmEFjU4tvT",
            "artist_name": "NyxTheShield",
            "input_artist_name": "NyxTheShield",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Soulless Heart (lofi Version)",
            "db_song_id": 6284,
        },
        {
            "service_id": "spotify",
            "artist_id": "45Thh01bYz4UDmEFjU4tvT",
            "artist_name": "NyxTheShield",
            "input_artist_name": "NyxTheShield",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Touhou  - Night of Nights / Flowering Night [Metal Remix by NyxTheShield]",
            "db_song_id": 5575,
        },
        {
            "service_id": "spotify",
            "artist_id": "45Thh01bYz4UDmEFjU4tvT",
            "artist_name": "NyxTheShield",
            "input_artist_name": "NyxTheShield",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Underverse OST - Inking Mistake [Ink vs Error Battle Theme]",
            "db_song_id": 1583,
        },
        {
            "service_id": "spotify",
            "artist_id": "6dewigIOIcG6m1XGsG4Mc3",
            "artist_name": "Paper Idol",
            "input_artist_name": "Paper Idol",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Castles",
            "db_song_id": 5689,
        },
        {
            "service_id": "spotify",
            "artist_id": "4DzC4sTTWf2juzeeMiFB8O",
            "artist_name": "Will Stetson",
            "input_artist_name": "Will Stetson",
            "song_id": None,
            "song_title": None,
            "input_song_title": "KING (English Cover)【Will Stetson】「Kanaria」",
            "db_song_id": 5975,
        },
        {
            "service_id": "spotify",
            "artist_id": "3V0ZQW0dNuVaFtbVYgSI24",
            "artist_name": "Claire Rosinkranz",
            "input_artist_name": "Claire Rosinkranz",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Backyard Boy (with Jeremy Zucker) [Official Video]",
            "db_song_id": 5654,
        },
        {
            "service_id": "spotify",
            "artist_id": "28VbaiiRmV4vk9O5ykVvCh",
            "artist_name": "Jordy Chandra",
            "input_artist_name": "Jordy Chandra",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Guizhong's Lullaby (Night Version)",
            "db_song_id": 5974,
        },
        {
            "service_id": "spotify",
            "artist_id": "2BQWHuvxG4kMYnfghdaCIy",
            "artist_name": "Fox Stevenson",
            "input_artist_name": "Fox Stevenson",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Don’t Care Crown",
            "db_song_id": 5989,
        },
        {
            "service_id": "spotify",
            "artist_id": "2BQWHuvxG4kMYnfghdaCIy",
            "artist_name": "Fox Stevenson",
            "input_artist_name": "Fox Stevenson",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Like That",
            "db_song_id": 5988,
        },
        {
            "service_id": "spotify",
            "artist_id": "2BQWHuvxG4kMYnfghdaCIy",
            "artist_name": "Fox Stevenson",
            "input_artist_name": "Fox Stevenson",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Out My Head (Fox Stevenson and Feint Remix)",
            "db_song_id": 5983,
        },
        {
            "service_id": "spotify",
            "artist_id": "5INjqkS1o8h1imAzPqGZBb",
            "artist_name": "Tame Impala",
            "input_artist_name": "Tame Impala",
            "song_id": None,
            "song_title": None,
            "input_song_title": "The Less I Know The Better (Audio)",
            "db_song_id": 5982,
        },
        {
            "service_id": "spotify",
            "artist_id": "2EtVScBCzjWga2zZeg3IHn",
            "artist_name": "little purr man",
            "input_artist_name": "little purr man",
            "song_id": None,
            "song_title": None,
            "input_song_title": "little purr man - i like to sleep",
            "db_song_id": 5980,
        },
        {
            "service_id": "spotify",
            "artist_id": "3Avni6DLpoxtanND8mG5t8",
            "artist_name": "Ghost and Pals",
            "input_artist_name": "Ghost and Pals",
            "song_id": None,
            "song_title": None,
            "input_song_title": "The Chattering Lack of Common Sense",
            "db_song_id": 5843,
        },
        {
            "service_id": "spotify",
            "artist_id": "2vlC4o7h61xlMUop6QCuvK",
            "artist_name": "Rory Webley",
            "input_artist_name": "Rory Webley",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Something Super Sweet (Official Audio)",
            "db_song_id": 5954,
        },
        {
            "service_id": "spotify",
            "artist_id": "4B1bjBU8CLkIBTYTRklo2u",
            "artist_name": "Chloe Adams",
            "input_artist_name": "Chloe Adams",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Chloe Adams - Dead To Me (Official Lyric Video)",
            "db_song_id": 5968,
        },
        {
            "service_id": "spotify",
            "artist_id": "4cmTpyy8yBFYDSaDa8R0Ki",
            "artist_name": "Hazerka",
            "input_artist_name": "Hazerka",
            "song_id": None,
            "song_title": None,
            "input_song_title": "En silence [Hazerka Mix] (feat. Ornella Tempesta)",
            "db_song_id": 5964,
        },
        {
            "service_id": "spotify",
            "artist_id": "7dGJo4pcD2V6oG8kP0tJRR",
            "artist_name": "Eminem",
            "input_artist_name": "Eminem",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Mockingbird [Official Music Video]",
            "db_song_id": 5965,
        },
        {
            "service_id": "spotify",
            "artist_id": "7dGJo4pcD2V6oG8kP0tJRR",
            "artist_name": "Eminem",
            "input_artist_name": "Eminem",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Venom",
            "db_song_id": 5675,
        },
        {
            "service_id": "spotify",
            "artist_id": "7dGJo4pcD2V6oG8kP0tJRR",
            "artist_name": "Eminem",
            "input_artist_name": "Eminem",
            "song_id": None,
            "song_title": None,
            "input_song_title": "When I'm Gone (Official Music Video)",
            "db_song_id": 1403,
        },
        {
            "service_id": "spotify",
            "artist_id": "164Uj4eKjl6zTBKfJLFKKK",
            "artist_name": "JVKE",
            "input_artist_name": "JVKE",
            "song_id": None,
            "song_title": None,
            "input_song_title": "JVKE - this is what falling in love feels like",
            "db_song_id": 5951,
        },
        {
            "service_id": "spotify",
            "artist_id": "6VuMaDnrHyPL1p4EHjYLi7",
            "artist_name": "Charlie Puth",
            "input_artist_name": "Charlie Puth",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Attention",
            "db_song_id": 5686,
        },
        {
            "service_id": "spotify",
            "artist_id": "6VuMaDnrHyPL1p4EHjYLi7",
            "artist_name": "Charlie Puth",
            "input_artist_name": "Charlie Puth",
            "song_id": None,
            "song_title": None,
            "input_song_title": "How Long",
            "db_song_id": 5684,
        },
        {
            "service_id": "spotify",
            "artist_id": "6P5NO5hzJbuOqSdyPB7SJM",
            "artist_name": "Ashe",
            "input_artist_name": "Ashe",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Moral of the Story feat. Niall Horan (Official Audio) (feat. Niall Horan)",
            "db_song_id": 5949,
        },
        {
            "service_id": "spotify",
            "artist_id": "7o2ZQYM7nTsaVdkXY38UAA",
            "artist_name": "Em Beihold",
            "input_artist_name": "Em Beihold",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Numb Little Bug (Piano Version Video)",
            "db_song_id": 5962,
        },
        {
            "service_id": "spotify",
            "artist_id": "69M1W8Nv8IcfWTFqZNIP5i",
            "artist_name": "leo.",
            "input_artist_name": "leo.",
            "song_id": None,
            "song_title": None,
            "input_song_title": "leo. - despair [official lyric video] (‘cause it’s not romantic, i swear)",
            "db_song_id": 5961,
        },
        {
            "service_id": "spotify",
            "artist_id": "4OTFxPi5CtWyj1NThDe6z5",
            "artist_name": "Weathers",
            "input_artist_name": "Weathers",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Happy Pills (NOW What's Next!)",
            "db_song_id": 5955,
        },
        {
            "service_id": "spotify",
            "artist_id": "2TM0qnbJH4QPhGMCdPt7fH",
            "artist_name": "Neck Deep",
            "input_artist_name": "Neck Deep",
            "song_id": None,
            "song_title": None,
            "input_song_title": "December",
            "db_song_id": 1384,
        },
        {
            "service_id": "spotify",
            "artist_id": "2TM0qnbJH4QPhGMCdPt7fH",
            "artist_name": "Neck Deep",
            "input_artist_name": "Neck Deep",
            "song_id": None,
            "song_title": None,
            "input_song_title": "December (Again) (feat. Mark Hoppus)",
            "db_song_id": 5814,
        },
        {
            "service_id": "spotify",
            "artist_id": "6UUoOFrzfmGZ50AP9SY97H",
            "artist_name": "Alma",
            "input_artist_name": "Alma",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Alma - T'es pas un Homme (clip officiel)",
            "db_song_id": 6205,
        },
        {
            "service_id": "spotify",
            "artist_id": "6UUoOFrzfmGZ50AP9SY97H",
            "artist_name": "Alma",
            "input_artist_name": "Alma",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Requiem (Eurovision Version)",
            "db_song_id": 6206,
        },
        {
            "service_id": "spotify",
            "artist_id": "37J1PlAkhRK7yrZUtqaUpQ",
            "artist_name": "Caravan Palace",
            "input_artist_name": "Caravan Palace",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Caravan Palace - Beatophone",
            "db_song_id": 5769,
        },
        {
            "service_id": "spotify",
            "artist_id": "12NSBgMVPKhwB8tDMsoYpP",
            "artist_name": "PR1SVX",
            "input_artist_name": "PR1SVX",
            "song_id": None,
            "song_title": None,
            "input_song_title": "CRYSTALS (Sped Up)",
            "db_song_id": 1365,
        },
        {
            "service_id": "spotify",
            "artist_id": "7gP3bB2nilZXLfPHJhMdvc",
            "artist_name": "Foster The People",
            "input_artist_name": "Foster The People",
            "song_id": None,
            "song_title": None,
            "input_song_title": "Pumped Up Kicks (Official Video)",
            "db_song_id": 5882,
        },
        {
            "service_id": "spotify",
            "artist_id": "12WiIkK6iBWyRefeKpMaKo",
            "artist_name": "ivycomb",
            "input_artist_name": "ivycomb",
            "song_id": None,
            "song_title": None,
            "input_song_title": "WELCOME TO THE ARCADE",
            "db_song_id": 1395,
        },
        {
            "service_id": "spotify",
            "artist_id": "6FBDaR13swtiWwGhX1WQsP",
            "artist_name": "blink-182",
            "input_artist_name": "blink-182",
            "song_id": None,
            "song_title": None,
            "input_song_title": "All The Small Things (Official Music Video)",
            "db_song_id": 1402,
        },
        {
            "service_id": "spotify",
            "artist_id": "1tt29X4uRBgHBhu9M1vEXM",
            "artist_name": "Anthony Amorim",
            "input_artist_name": "Anthony Amorim",
            "song_id": None,
            "song_title": None,
            "input_song_title": "2004 (feat. Parrotfish)",
            "db_song_id": 5943,
        },
    ]

    # identified = identify_songs(unidentified_songs_db)
    # pprint(identified)
    # print(sp.artist_albums("2SW5wli9uAsYHQnezGESFB")['items'])


    input_titles = [
        "00:00 - 04:21 snafu - why as soon as we become so close we have to say goodbye",
        "04:21 - 06:58 Ftlframe - ANGEL TEARS",
        "06:58 - 09:26 iwakura - illusion of control ",
        "09:26 - 15:23 glitchtrode - Lost fragments",
        "15:23 - 21:59 Sewerslvt - all the joy in life was gone once you left",
        "21:59 - 25:26 4banga - Unleash",
        "25:26 - 28:12 Dontlookatmyface - Maria",
        "28:12 - 34:47 Sewerslvt - Purple Hearts in Her Eyes ",
        "34:47 - 40:52 Iwakura - fading ",
        "40:52 - 46:59 AgonyOST, Sewerslvt - Light Stops Dripping Through The Stars ",
        "46:59 - 49:18 Tokyopill - Wish ",
        "49:18 - 50:34 Enkei - daydreamer ",
        "50:34 - 53:13 aak3 - lonely destruction ",
        "53:13 - 56:08 Purity Filter - Chrystalis",
        "56:08 - 01:02:38 Sewerslvt - Never Existed ",
        "01:02:38 - 01:06:01 usedcvnt - wonderfulcore ",
        "01:06:01 - 01:07:28 Aeriu Ika - Fata Morgana",
    ]
    #instant_playlist = {
    #    "playlist_name": "breakkk",
    #    "songs": songs_from_list(input_titles),
    #}

    breakcore = {
        "playlist_name": "breakkk",
        "songs": [
            {
                "service_id": "spotify",
                "artist_id": "6D9QrghftPFUTOPkxAJfSp",
                "artist_name": "snafu",
                "song_id": "5qzGqhLV6fHbXpSdqqal6w",
                "song_title": "why as soon as we become so close we have to say goodbye",
            },
            {
                "service_id": "spotify",
                "artist_id": "0C1KLj4tJZ6rBGgPNEDg8U",
                "artist_name": "Emi Fujita",
                "song_id": "6JU802sED2JygZBdMk1UPG",
                "song_title": "Best of My Love",
            },
            {
                "service_id": "spotify",
                "artist_id": "5Mu0EMEsUIVE132pNMywns",
                "artist_name": "Skinny Puppy",
                "song_id": "5sXLtql3CzT70LpBJlc2Tf",
                "song_title": "Spahn Dirge - Live",
            },
            {
                "service_id": "spotify",
                "artist_id": "3GLfDAV3PJ4jMMZ0UUjwig",
                "artist_name": "Monstercat Call of the Wild",
                "song_id": "7cOzqk5mAKnSYqHrjlOyQU",
                "song_title": "Monstercat Podcast Ep. 100",
            },
            {
                "service_id": "spotify",
                "artist_id": "30F64wQIHvLiFTGaNZ73nU",
                "artist_name": "Sewerslvt",
                "song_id": "3oW5JBbjGs42jzCkw4Di8X",
                "song_title": "all the joy in life was gone once you left",
            },
            {
                "service_id": "spotify",
                "artist_id": "0sPI6LfHEgIVsnTBZOMEvI",
                "artist_name": "Kids TV",
                "song_id": "3rrL159tB7ko4J0SfxwKQH",
                "song_title": "Numbers Song (To 100)",
            },
            {
                "service_id": "spotify",
                "artist_id": "5aIqB5nVVvmFsvSdExz408",
                "artist_name": "Johann Sebastian Bach",
                "song_id": "6Kle3fTvXPtvjd5FHU8LGQ",
                "song_title": 'Christmas Oratorio, BWV 248 / Part One - For The First Day Of Christmas: No. 7 Chorale: "Er ist auf Erden kommen arm", Recitativ (Bass): Wer will die Liebe recht erhöhn"',
            },
            {
                "service_id": "spotify",
                "artist_id": "0O0g9JMOVNoIgLG6dgaYMY",
                "artist_name": "Robyn Hitchcock",
                "song_id": "2jvY9Bs10J3ZldkfyuVSMa",
                "song_title": "Linctus House",
            },
            {
                "service_id": "spotify",
                "artist_id": "1RlnzIazwomBpkg7vHVs2s",
                "artist_name": "Omar Hisham",
                "song_id": "2Bo1bC4f6YNxXpHtVLO54a",
                "song_title": "Surah Ar-Rahman (Be Heaven)",
            },
            {
                "service_id": "spotify",
                "artist_id": "1XUDvMVQEJ5HkfG3qzN6yt",
                "artist_name": "AgonyOST",
                "song_id": "6OHWYgAcTpBhCAdShyretc",
                "song_title": "Light Stops Dripping Through The Stars - Sewerslvt Remix",
            },
            {
                "service_id": "spotify",
                "artist_id": "0sKsReKseslDlhxmbN6wLk",
                "artist_name": "BabyTron",
                "song_id": "0yYYco9yk2nclC82ioryu8",
                "song_title": "100 Bars",
            },
            {
                "service_id": "spotify",
                "artist_id": "5wBKrKLB98LeDOvP2ao7Za",
                "artist_name": "Sheikh Abdelrahman Al-Laithy",
                "song_id": "0mqaPlBihm5Ayz2nfld1RA",
                "song_title": "Surah Al-Kahfi",
            },
            {
                "service_id": "spotify",
                "artist_id": "4v1YZL83eLyemlt32wWAoA",
                "artist_name": "Keren Ann",
                "song_id": "6UdMfheesYFP4pflsoDP4n",
                "song_title": "101",
            },
            {
                "service_id": "spotify",
                "artist_id": "35he9yh8ik3SiRr3RnafUT",
                "artist_name": "Sigmund Groven",
                "song_id": "1VRS5oBCPvpxyEC77fgncD",
                "song_title": "Londonderry Air",
            },
            {
                "service_id": "spotify",
                "artist_id": "3GLfDAV3PJ4jMMZ0UUjwig",
                "artist_name": "Monstercat Call of the Wild",
                "song_id": "7cOzqk5mAKnSYqHrjlOyQU",
                "song_title": "Monstercat Podcast Ep. 100",
            },
            {
                "service_id": "spotify",
                "artist_id": "3GLfDAV3PJ4jMMZ0UUjwig",
                "artist_name": "Monstercat Call of the Wild",
                "song_id": "7cOzqk5mAKnSYqHrjlOyQU",
                "song_title": "Monstercat Podcast Ep. 100",
            },
            {
                "service_id": "spotify",
                "artist_id": "3GLfDAV3PJ4jMMZ0UUjwig",
                "artist_name": "Monstercat Call of the Wild",
                "song_id": "7cOzqk5mAKnSYqHrjlOyQU",
                "song_title": "Monstercat Podcast Ep. 100",
            },
        ],
    }

    # pprint(input_playlist())
    def create_playlist(playlist):
        print(playlist)
        pprint(playlist["songs"])
        user_id = sp.current_user()["id"]
        spotify_playlist = sp.user_playlist_create(user_id, playlist["playlist_name"], False)
        sp.playlist_add_items(
            playlist_id=spotify_playlist["id"],
            items=[song["song_id"] for song in playlist["songs"]],
        )
    print(songs_from_list("a"))
    
    new_playlist = input_playlist(songs_from_list=songfromlist)
    create_playlist(new_playlist)
